/*
 * ADC_config.h
 *
 *  Created on: Oct 27, 2023
 *      Author: AhmedAbogabl
 */

#ifndef MCAL_ADC_INCLUDES_ADC_CONFIG_H_
#define MCAL_ADC_INCLUDES_ADC_CONFIG_H_



#define ADC_PRESCALER_2   0
#define ADC_PRESCALER_4   1
#define ADC_PRESCALER_8   2
#define ADC_PRESCALER_16  3
#define ADC_PRESCALER_32  4
#define ADC_PRESCALER_64  5
#define ADC_PRESCALER_128 6

#define ADC_PRESCALER_MODE ADC_PRESCALER_64



#define ADC_AREF	0
#define ADC_AVCC 	1
#define ADC_INTERNAL_VREF_WITH_EXTERNAL_CAP_AT_AREF 3


#define ADC_AREF_MODE   ADC_AVCC


#define ADC_RIGHT_ADJUST_THE_RESULT 0
#define ADC_LEFT_ADJUST_THE_RESULT 1
#define ADC_RESULT_ADJUSTMENT_MODE ADC_LEFT_ADJUST_THE_RESULT
#endif /* MCAL_ADC_INCLUDES_ADC_CONFIG_H_ */
